networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge

services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - public_network

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__PostgresConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Email__SmtpHost=${EMAIL_SMTP_HOST}
      - Email__SmtpPort=${EMAIL_SMTP_PORT}
      - Email__Usuario=${EMAIL_USUARIO}
      - Email__Senha=${EMAIL_SENHA}
      - Email__De=${EMAIL_DE}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiresInMinutes=${JWT_EXPIRES_IN_MINUTES}
      - AllowedHosts=${ALLOWED_HOSTS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - private_network
      - public_network

  db:
    image: postgres:15
    container_name: database
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - private_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: