
networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge

services:
  frontend:
    image: jrrs1/frontend-labon:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - public_network

  backend:
    platform: linux/amd64
    image: jrrs1/backend-labon:latest
    container_name: backend
    depends_on:
      - db-postgres
    restart: always
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/labsolos
    networks:
      - private_network
      - public_network



  db-postgres:
    image: postgres:15
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-labsolos
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - private_network  

volumes:
  pg_data:
