version: "3.8"

services:
  frontend:
    image: jrrs1/frontend-labon:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: jrrs1/backend-labon:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
#    environment:
#      - DATABASE_URL=postgres://postgres:postgres@db:5432/labsolos

#  db:
#    image: postgres:15
#    container_name: database
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: labsolos
#    volumes:
#      - pg_data:/var/lib/postgresql/data

#volumes:
#  pg_data:
