// <auto-generated />
using System;
using LabSolos_Server_DotNet8.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabSolos_Server_DotNet8.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831132518_UserDataContracts")]
    partial class UserDataContracts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprovadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AprovadorId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DadosRequisicao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DadosResposta")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EnderecoIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("MotivoSuspeita")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("integer");

                    b.Property<string>("Origem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Suspeita")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("TempoSessao")
                        .HasColumnType("interval");

                    b.Property<int?>("TentativasAcesso")
                        .HasColumnType("integer");

                    b.Property<int>("TipoAcao")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataHora");

                    b.HasIndex("EnderecoIP");

                    b.HasIndex("NivelRisco");

                    b.HasIndex("Suspeita");

                    b.HasIndex("TipoAcao");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("DataHora", "UsuarioId", "TipoAcao");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFabricacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkAcao")
                        .HasColumnType("text");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoReferencia")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("Lida");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Catmat")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataFabricacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("text");

                    b.Property<string>("LocalizacaoProduto")
                        .HasColumnType("text");

                    b.Property<int?>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Quantidade")
                        .HasColumnType("real");

                    b.Property<float>("QuantidadeMinima")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimaModificacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnidadeMedida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<int>("Tipo").HasValue(2);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.ProdutoEmprestado", b =>
                {
                    b.Property<int>("EmprestimoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("EmprestimoId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutosEmprestados");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataIngresso")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ExigeTrocaSenha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("NivelUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TokenExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenRedefinicaoHash")
                        .HasColumnType("text")
                        .HasColumnName("TokenRedefinicaoHash");

                    b.Property<long>("VersaoSessao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<int>("TipoUsuario").HasValue(2);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Quimico", b =>
                {
                    b.HasBaseType("LabSolos_Server_DotNet8.Models.Produto");

                    b.Property<int>("Cor")
                        .HasColumnType("integer");

                    b.Property<float?>("Densidade")
                        .HasColumnType("real");

                    b.Property<int?>("EstadoFisico")
                        .HasColumnType("integer");

                    b.Property<string>("FormulaQuimica")
                        .HasColumnType("text");

                    b.Property<string>("GrauPureza")
                        .HasColumnType("text");

                    b.Property<int>("Grupo")
                        .HasColumnType("integer");

                    b.Property<int>("Odor")
                        .HasColumnType("integer");

                    b.Property<float?>("PesoMolecular")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Vidraria", b =>
                {
                    b.HasBaseType("LabSolos_Server_DotNet8.Models.Produto");

                    b.Property<int>("Altura")
                        .HasColumnType("integer");

                    b.Property<float?>("Capacidade")
                        .HasColumnType("real");

                    b.Property<int>("Formato")
                        .HasColumnType("integer");

                    b.Property<bool?>("Graduada")
                        .HasColumnType("boolean");

                    b.Property<int>("Material")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Academico", b =>
                {
                    b.HasBaseType("LabSolos_Server_DotNet8.Models.Usuario");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Curso")
                        .HasColumnType("text");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Administrador", b =>
                {
                    b.HasBaseType("LabSolos_Server_DotNet8.Models.Usuario");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Emprestimo", b =>
                {
                    b.HasOne("LabSolos_Server_DotNet8.Models.Usuario", "Aprovador")
                        .WithMany("EmprestimosAprovados")
                        .HasForeignKey("AprovadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LabSolos_Server_DotNet8.Models.Usuario", "Solicitante")
                        .WithMany("EmprestimosSolicitados")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aprovador");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.LogAuditoria", b =>
                {
                    b.HasOne("LabSolos_Server_DotNet8.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Notificacao", b =>
                {
                    b.HasOne("LabSolos_Server_DotNet8.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Produto", b =>
                {
                    b.HasOne("LabSolos_Server_DotNet8.Models.Lote", "Lote")
                        .WithMany("Produtos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.ProdutoEmprestado", b =>
                {
                    b.HasOne("LabSolos_Server_DotNet8.Models.Emprestimo", "Emprestimo")
                        .WithMany("Produtos")
                        .HasForeignKey("EmprestimoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabSolos_Server_DotNet8.Models.Produto", "Produto")
                        .WithMany("ProdutoEmprestado")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprestimo");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Usuario", b =>
                {
                    b.HasOne("LabSolos_Server_DotNet8.Models.Usuario", "Responsavel")
                        .WithMany("Dependentes")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Emprestimo", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Lote", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Produto", b =>
                {
                    b.Navigation("ProdutoEmprestado");
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Usuario", b =>
                {
                    b.Navigation("Dependentes");

                    b.Navigation("EmprestimosAprovados");

                    b.Navigation("EmprestimosSolicitados");
                });
#pragma warning restore 612, 618
        }
    }
}
