CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE TABLE "Lotes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CodigoLote" text NOT NULL,
        "Fornecedor" text,
        "DataFabricacao" timestamp with time zone,
        "DataValidade" timestamp with time zone,
        "DataEntrada" timestamp with time zone,
        CONSTRAINT "PK_Lotes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "NomeCompleto" text NOT NULL,
        "Email" text NOT NULL,
        "SenhaHash" text NOT NULL,
        "Telefone" text,
        "DataIngresso" timestamp with time zone,
        "NivelUsuario" integer NOT NULL,
        "TipoUsuario" integer NOT NULL,
        "Status" integer NOT NULL,
        "ResponsavelId" integer,
        "TokenRedefinicao" text,
        "TokenExpiracao" timestamp with time zone,
        "Instituicao" text,
        "Cidade" text,
        "Curso" text,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Usuarios_Usuarios_ResponsavelId" FOREIGN KEY ("ResponsavelId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE TABLE "Produtos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Catmat" text,
        "NomeProduto" text NOT NULL,
        "Fornecedor" text,
        "Tipo" integer NOT NULL,
        "Quantidade" real NOT NULL,
        "QuantidadeMinima" real NOT NULL,
        "UnidadeMedida" integer NOT NULL,
        "DataFabricacao" timestamp with time zone,
        "DataValidade" timestamp with time zone,
        "LocalizacaoProduto" text,
        "Status" integer NOT NULL,
        "UltimaModificacao" timestamp with time zone NOT NULL,
        "LoteId" integer,
        "EstadoFisico" integer,
        "Cor" integer,
        "Odor" integer,
        "Densidade" real,
        "PesoMolecular" real,
        "GrauPureza" text,
        "FormulaQuimica" text,
        "Grupo" integer,
        "Material" integer,
        "Formato" integer,
        "Altura" integer,
        "Capacidade" real,
        "Graduada" boolean,
        CONSTRAINT "PK_Produtos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Produtos_Lotes_LoteId" FOREIGN KEY ("LoteId") REFERENCES "Lotes" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE TABLE "Emprestimos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DataRealizacao" timestamp with time zone NOT NULL,
        "DataDevolucao" timestamp with time zone,
        "DataAprovacao" timestamp with time zone,
        "Status" integer NOT NULL,
        "SolicitanteId" integer NOT NULL,
        "AprovadorId" integer,
        CONSTRAINT "PK_Emprestimos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Emprestimos_Usuarios_AprovadorId" FOREIGN KEY ("AprovadorId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Emprestimos_Usuarios_SolicitanteId" FOREIGN KEY ("SolicitanteId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE TABLE "LogsAuditoria" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DataHora" timestamp with time zone NOT NULL,
        "Acao" character varying(50) NOT NULL,
        "Recurso" character varying(100) NOT NULL,
        "Detalhes" character varying(500),
        "EnderecoIP" character varying(45) NOT NULL,
        "UserAgent" character varying(500),
        "TipoAcao" integer NOT NULL,
        "NivelRisco" integer NOT NULL,
        "Suspeita" boolean NOT NULL,
        "MotivoSuspeita" character varying(1000),
        "UsuarioId" integer,
        "DadosRequisicao" character varying(2000),
        "DadosResposta" character varying(1000),
        "TempoSessao" interval,
        "TentativasAcesso" integer,
        "Origem" character varying(100),
        CONSTRAINT "PK_LogsAuditoria" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LogsAuditoria_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE TABLE "Notificacoes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Titulo" text NOT NULL,
        "Mensagem" text NOT NULL,
        "Tipo" integer NOT NULL,
        "UsuarioId" integer,
        "Lida" boolean NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataLeitura" timestamp with time zone,
        "LinkAcao" text,
        "ReferenciaId" integer,
        "TipoReferencia" text,
        CONSTRAINT "PK_Notificacoes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notificacoes_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE TABLE "ProdutosEmprestados" (
        "EmprestimoId" integer NOT NULL,
        "ProdutoId" integer NOT NULL,
        "Quantidade" integer NOT NULL,
        CONSTRAINT "PK_ProdutosEmprestados" PRIMARY KEY ("EmprestimoId", "ProdutoId"),
        CONSTRAINT "FK_ProdutosEmprestados_Emprestimos_EmprestimoId" FOREIGN KEY ("EmprestimoId") REFERENCES "Emprestimos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProdutosEmprestados_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produtos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_Emprestimos_AprovadorId" ON "Emprestimos" ("AprovadorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_Emprestimos_SolicitanteId" ON "Emprestimos" ("SolicitanteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_LogsAuditoria_DataHora" ON "LogsAuditoria" ("DataHora");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_LogsAuditoria_DataHora_UsuarioId_TipoAcao" ON "LogsAuditoria" ("DataHora", "UsuarioId", "TipoAcao");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_LogsAuditoria_EnderecoIP" ON "LogsAuditoria" ("EnderecoIP");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_LogsAuditoria_NivelRisco" ON "LogsAuditoria" ("NivelRisco");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_LogsAuditoria_Suspeita" ON "LogsAuditoria" ("Suspeita");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_LogsAuditoria_TipoAcao" ON "LogsAuditoria" ("TipoAcao");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_LogsAuditoria_UsuarioId" ON "LogsAuditoria" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_Notificacoes_DataCriacao" ON "Notificacoes" ("DataCriacao");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_Notificacoes_Lida" ON "Notificacoes" ("Lida");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_Notificacoes_UsuarioId" ON "Notificacoes" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_Produtos_LoteId" ON "Produtos" ("LoteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_ProdutosEmprestados_ProdutoId" ON "ProdutosEmprestados" ("ProdutoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    CREATE INDEX "IX_Usuarios_ResponsavelId" ON "Usuarios" ("ResponsavelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172637_InitialSchemaBaseline') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260830172637_InitialSchemaBaseline', '9.0.19');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172718_CredentialLifecycle') THEN
    ALTER TABLE "Usuarios" RENAME COLUMN "TokenRedefinicao" TO "TokenRedefinicaoHash";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172718_CredentialLifecycle') THEN
    ALTER TABLE "Usuarios" ADD "ExigeTrocaSenha" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172718_CredentialLifecycle') THEN
    ALTER TABLE "Usuarios" ADD "VersaoSessao" bigint NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172718_CredentialLifecycle') THEN
    UPDATE "Usuarios" SET "TokenRedefinicaoHash" = NULL, "TokenExpiracao" = NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830172718_CredentialLifecycle') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260830172718_CredentialLifecycle', '9.0.19');
    END IF;
END $EF$;
COMMIT;
