// <auto-generated />
using System;
using LabSolos_Server_DotNet8.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabSolos_Server_DotNet8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241010023452_AddGrupoToQuimicos")]
    partial class AddGrupoToQuimicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalizacaoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantidade")
                        .HasColumnType("REAL");

                    b.Property<double>("QuantidadeMinima")
                        .HasColumnType("REAL");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaModificacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Quimico", b =>
                {
                    b.HasBaseType("LabSolos_Server_DotNet8.Models.Produto");

                    b.Property<string>("Catmat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Grupo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadeMedida")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(0);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "Q123",
                            DataValidade = new DateTime(2025, 10, 9, 23, 34, 51, 336, DateTimeKind.Local).AddTicks(6955),
                            LocalizacaoProduto = "Prateleira A",
                            Lote = "Lote1",
                            Marca = "Marca X",
                            Quantidade = 100.0,
                            QuantidadeMinima = 10.0,
                            Status = true,
                            Tipo = 0,
                            UltimaModificacao = new DateTime(2024, 10, 9, 23, 34, 51, 336, DateTimeKind.Local).AddTicks(7005),
                            Catmat = "CATMAT-01",
                            Formula = "H2O",
                            Grupo = 0,
                            UnidadeMedida = 0
                        });
                });

            modelBuilder.Entity("LabSolos_Server_DotNet8.Models.Vidraria", b =>
                {
                    b.HasBaseType("LabSolos_Server_DotNet8.Models.Produto");

                    b.Property<double>("Volumetria")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Codigo = "V456",
                            DataValidade = new DateTime(2026, 10, 9, 23, 34, 51, 336, DateTimeKind.Local).AddTicks(7224),
                            LocalizacaoProduto = "Prateleira B",
                            Lote = "Lote2",
                            Marca = "Marca Y",
                            Quantidade = 50.0,
                            QuantidadeMinima = 5.0,
                            Status = true,
                            Tipo = 1,
                            UltimaModificacao = new DateTime(2024, 10, 9, 23, 34, 51, 336, DateTimeKind.Local).AddTicks(7230),
                            Volumetria = 500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
