name: CI/CD Workflow

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
    # Rodar somente se houver mudanças no diretório `frontend/`
    if: ${{ github.event_name == 'push' && github.event.commits.*.modified | join(' ') contains 'frontend/' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm test

      - name: Build Docker image for frontend
        run: |
          docker build -t jrss1/frontend-labon:latest ./frontend

      - name: Push Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker push jrrs1/frontend-labon:latest

  backend:
    # Rodar somente se houver mudanças no diretório `backend/`
    if: ${{ github.event_name == 'push' && github.event.commits.*.modified | join(' ') contains 'backend/' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: |
          cd backend
          dotnet restore

      - name: Run tests
        run: |
          cd backend
          dotnet test

      - name: Build Docker image for backend
        run: |
          docker build -t jrss1/backend-labon:latest ./backend

      - name: Push Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker push jrrs1/backend-labon:latest
