name: CI/CD Workflow

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
    # Rodar somente se houver mudanças no diretório `frontend/`
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint
        run: |
          cd frontend
          npm run lint

      - name: Build Docker image for frontend
        run: |
          docker build -t jrrs1/frontend-labon:latest -f frontend/Dockerfile frontend

      - name: Login Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan backend image with Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh 
          docker scout quickview jrrs1/backend-labon:latest
          docker scout policy jrrs1/backend-labon:latest \
            --fail-on=critical,high \

      - name: Push Docker image to Docker Hub
        run: |
          docker push jrrs1/frontend-labon:latest

  backend:
    # Rodar somente se houver mudanças no diretório `backend/`
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: |
          cd backend/LabSolos-Server-DotNet8
          dotnet restore

      - name: Run tests
        run: |
          cd backend/LabSolos-Server-DotNet8
          dotnet test

      - name: Build Docker image for backend
        run: |
          docker build -t jrrs1/backend-labon:latest -f backend/Dockerfile backend

      - name: Login Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan backend image with Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          docker scout quickview jrrs1/backend-labon:latest
          docker scout policy jrrs1/backend-labon:latest \
            --fail-on=critical,high \

      - name: Push Docker image to Docker Hub
        run: |
          docker push jrrs1/backend-labon:latest
